#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/staged_box"

begin
  StagedBox::Command.run
rescue StandardError => ex
  raise e if $DEBUG

  warn ex.message
  warn ex.backtrace.join("\n")
  exit 1
end
